const siteConfig = {
  name: "Podgorica Car Hire",
  tagline: "Drive from Montenegro's Capital",
  domain: "podgoricacarhire.com",
  phone: "",
  email: "info@podgoricacarhire.com",
  address: "Tabacina BB, Kotor, 85330",

  hero: {
    headline: "Podgorica Car Hire",
    subheadline: "Pick up at Podgorica Airport — gateway to Durmitor, Lake Skadar, and the Adriatic coast.",
    image: "/img/hero-podgorica.webp",
  },

  cars: [
    {
      id: 1,
      slug: "vw-polo",
      name: "VW Polo",
      category: "Economy",
      price: 25,
      image: "/img/pexels-1035108.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Air Conditioning", "Bluetooth Audio", "USB Charging", "Central Locking"],
      popular: false,
    },
    {
      id: 2,
      slug: "skoda-octavia",
      name: "Skoda Octavia",
      category: "Mid-Size",
      price: 35,
      image: "/img/pexels-116675.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 4,
      ac: true,
      features: ["Automatic Transmission", "Cruise Control", "Parking Sensors", "Large Boot"],
      popular: true,
    },
    {
      id: 3,
      slug: "toyota-corolla",
      name: "Toyota Corolla",
      category: "Mid-Size",
      price: 38,
      image: "/img/pexels-170811.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Hybrid",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Hybrid Engine", "Reversing Camera", "Apple CarPlay", "Keyless Start"],
      popular: false,
    },
    {
      id: 4,
      slug: "mercedes-c-class",
      name: "Mercedes C-Class",
      category: "Premium",
      price: 65,
      image: "/img/pexels-120049.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Leather Seats", "Navigation System", "Premium Sound", "Heated Seats"],
      popular: true,
    },
    {
      id: 5,
      slug: "jeep-renegade",
      name: "Jeep Renegade",
      category: "SUV",
      price: 55,
      image: "/img/pexels-1638459.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["4x4 Drive", "Hill Descent Control", "Roof Rails", "Off-Road Mode"],
      popular: false,
    },
    {
      id: 6,
      slug: "bmw-x3",
      name: "BMW X3",
      category: "Premium SUV",
      price: 85,
      image: "/img/pexels-892522.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 4,
      ac: true,
      features: ["Panoramic Roof", "Adaptive Cruise", "360 Camera", "Sport Mode"],
      popular: false,
    },
    {
      id: 7,
      slug: "fiat-500",
      name: "Fiat 500",
      category: "City",
      price: 20,
      image: "/img/pexels-1007410.jpg",
      seats: 4,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 2,
      luggage: 1,
      ac: true,
      features: ["Compact Size", "Easy Parking", "Sunroof", "Bluetooth"],
      popular: false,
    },
    {
      id: 8,
      slug: "vw-transporter",
      name: "VW Transporter",
      category: "Van",
      price: 70,
      image: "/img/pexels-2533092.jpg",
      seats: 9,
      transmission: "Manual",
      fuel: "Diesel",
      doors: 4,
      luggage: 6,
      ac: true,
      features: ["9 Seats", "Airport Shuttle Ready", "Sliding Doors", "Ample Storage"],
      popular: false,
    },
  ],

  features: [
    { icon: "map-pin", title: "Airport Pickup", description: "Keys in hand within 10 minutes of landing at TGD. The mountains are waiting." },
    { icon: "shield-check", title: "Full Insurance", description: "Full coverage with zero excess option — built for mountain switchbacks, canyon roads, and everything in between." },
    { icon: "clock", title: "24/7 Support", description: "Snowed in above \u017dabljak? We've seen it before. Call any time." },
    { icon: "ban", title: "No Hidden Fees", description: "Winter extras like snow chains are priced upfront, never added at the counter. What you see is what you pay." },
    { icon: "refresh-cw", title: "Free Cancellation", description: "Ryanair rescheduled? Mountain pass closed by snow? Cancel up to 24 hours before for a full refund." },
    { icon: "globe", title: "Cross-Border", description: "Serbia (Prijepolje, 2 hrs), Albania (Shkodra, 1.5 hrs), Kosovo (Pe\u0107, 3 hrs) — Green Card included, just tell us at booking." },
  ],

  testimonials: [
    { name: "Erik & Marte Solberg", location: "Oslo, Norway", text: "We flew into TGD specifically to hike Durmitor and walk the rim of Tara Canyon. The 4x4 was ready in minutes and handled the mountain roads to \u017dabljak without a single complaint. Booking was simple and the price was better than anything we found back home.", rating: 5, avatar: "/img/avatar-1.webp" },
    { name: "Lukas Berger", location: "Vienna, Austria", text: "Solo road trip from Podgorica Airport up through Mora\u010Da Canyon to Ostrog Monastery — one of the most dramatic drives I've ever done. The car was immaculate and picking it up at TGD took less than 10 minutes. I'll use this service every time I fly Wizz Air into Montenegro.", rating: 5, avatar: "/img/avatar-2.webp" },
    { name: "Beatriz & Joana", location: "Lisbon, Portugal", text: "We booked a beach trip but ended up spending two days exploring Lake Skadar wine villages and somehow found ourselves on a mountain road above Cetinje at sunset. Best accidental detour ever. The car made it all possible and the booking was completely stress-free.", rating: 5, avatar: "/img/avatar-3.webp" },
  ],

  faq: [
    { q: "What documents do I need?", a: "A valid driving licence showing Latin-script details, your passport, and a physical credit card issued in the main driver's name. If your licence was issued outside the EU, an International Driving Permit is strongly recommended alongside your national licence. Photocopies and digital licences stored on a phone are not accepted at pickup." },
    { q: "Can I drive to Serbia or Albania?", a: "Yes \u2014 cross-border travel is permitted to Serbia, Albania, Kosovo, Bosnia, and Croatia. The main border crossings near Podgorica are Dra\u010Denovac for Serbia and Hani i Hotit for Albania. Let us know at booking so we can prepare the Green Card and any additional paperwork in advance." },
    { q: "Is there a minimum age?", a: "The minimum rental age is 21, with at least 2 years of driving experience. Drivers aged 21\u201324 pay a young driver supplement; the exact rate depends on the vehicle category and is shown clearly during the search before you confirm anything." },
    { q: "What's included in the price?", a: "All vehicles include third-party liability insurance, and most include CDW (Collision Damage Waiver) in the base rate. VAT, the mandatory equipment kit (first aid, warning triangle, reflective vest), and a clearly stated fuel policy are all included. Mileage terms vary by vehicle and are shown before booking. Zero-excess upgrades are available as an add-on." },
    { q: "How does pickup work at TGD?", a: "Podgorica Airport (TGD) is a compact single-terminal building \u2014 arrivals are straightforward. Our agent meets you in the arrivals hall holding a board with your name. The car is parked just outside the terminal. From wheels-down to driving away typically takes under 10 minutes." },
    { q: "Can I drop off at a different location?", a: "Yes \u2014 one-way rentals are available across 28 destinations in Montenegro. Choose your preferred pickup and dropoff points during booking. One-way fees, where they apply, are shown transparently before you confirm." },
    { q: "What is the cancellation policy?", a: "Standard vehicles: free cancellation up to 7 days before pickup. Luxury cars and convertibles: free cancellation up to 30 days before. A 6% payment processing fee applies to all cancellations regardless of timing. If a mountain pass closure or severe weather forces a change of plans, contact us \u2014 we'll do what we can." },
    { q: "Is a deposit required?", a: "Deposit requirements at TGD vary between zero and \u20AC300 depending on the vehicle tier. The deposit must be blocked on a physical credit card (not debit or prepaid) in the main driver's name at the time of pickup, and is fully released once the car is returned undamaged. The exact amount for your chosen vehicle is shown in the booking summary." },
    { q: "What happens if I exceed the mileage limit?", a: "Vehicles with a kilometre cap charge a per-km rate for any distance above the agreed limit. The rate is listed in the vehicle terms before you book. If you're planning long mountain drives \u2014 Durmitor, Tara Canyon, the Albanian border \u2014 check the mileage terms carefully or look for an unlimited-mileage option." },
    { q: "Do I need snow chains for mountain roads?", a: "From November to March, snow chains or winter tyres are legally required on mountain roads above 1,000 m in Montenegro. This includes the road to \u017dabljak and Durmitor National Park. If you're heading into the mountains in winter, let us know at booking and we'll equip the car accordingly. Also note: Nik\u0161i\u0107 is the last reliable fuel stop before Durmitor \u2014 fill up there." },
    { q: "How much do I pay upfront?", a: "A deposit of 15\u201320% of the total rental cost is charged at booking to secure your reservation. The remaining balance is settled directly with the rental agent at TGD pickup. No surprise charges at the counter \u2014 the split is shown clearly before you confirm." },
    { q: "Can I rent without a credit card?", a: "A small number of vehicles in our fleet are available to renters without a credit card \u2014 these are clearly marked in the search results. For most vehicles, however, a physical credit card in the driver's name is required for the security deposit at pickup." },
  ],

  locations: [
    { name: "Podgorica Airport", tag: "Most Popular" },
    { name: "City Centre", tag: "" },
    { name: "Millennium Bridge Area", tag: "" },
  ],

  destinations: [
    {
      name: "Podgorica Airport",
      slug: "podgorica-airport",
      tag: "Most Popular",
      desc: "Our main hub. We meet you at arrivals.",
      image: "/img/podgorica-airport.webp",
    },
    {
      name: "Lake Skadar",
      slug: "lake-skadar",
      tag: "30 Minutes",
      desc: "The Balkans' largest lake and a national park.",
      image: "/img/lake-skadar.webp",
    },
    {
      name: "Cetinje",
      slug: "cetinje",
      tag: "35 Minutes",
      desc: "Montenegro's old royal capital in the mountains.",
      image: "/img/cetinje-town.webp",
    },
    {
      name: "Budva",
      slug: "budva",
      tag: "1 Hour",
      desc: "Riviera beaches and the old town walls.",
      image: "/img/budva-coast.webp",
    },
    {
      name: "Kotor",
      slug: "kotor",
      tag: "1.5 Hours",
      desc: "UNESCO walled city on the Bay of Kotor.",
      image: "/img/kotor-bay.webp",
    },
    {
      name: "Durmitor",
      slug: "durmitor",
      tag: "2.5 Hours",
      desc: "UNESCO national park — mountains, lakes, and canyons.",
      image: "/img/durmitor-mountains.webp",
    },
    {
      name: "Ostrog Monastery",
      slug: "ostrog-monastery",
      tag: "45 Minutes",
      desc: "Cliff-carved monastery — Montenegro's most visited pilgrimage site.",
      image: "/img/ostrog-monastery.webp",
    },
    {
      name: "Niksic",
      slug: "niksic",
      tag: "1 Hour",
      desc: "Montenegro's second city — gateway to the north.",
      image: "/img/niksic-town.webp",
    },
  ],
};

export default siteConfig;
