const siteConfig = {
  name: "Podgorica Car Hire",
  tagline: "Drive from Montenegro's Capital",
  domain: "podgoricacarhire.com",
  phone: "",
  email: "info@podgoricacarhire.com",
  address: "Tabacina BB, Kotor, 85330",

  hero: {
    headline: "Podgorica Car Hire",
    subheadline: "Pick up at Podgorica Airport, gateway to Durmitor, Lake Skadar, and the Adriatic coast.",
    image: "/img/hero-podgorica.webp",
  },

  cars: [
    {
      id: 1,
      slug: "vw-polo",
      typeGroup: "economy",
      name: "VW Polo",
      category: "Economy",
      tagline: "Tidy city hatch for TGD, capital errands and the Skadar lake run",
      lede: "Fits the free on-street bays around Podgorica's boulevards and holds 130 km/h down the Sozina toll motorway without fuss.",
      price: 25,
      image: "/img/fleet/vw-polo.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Air Conditioning", "Bluetooth Audio", "USB Charging", "Central Locking"],
      details: {
        engine: "1.0 L TSI 3-cyl turbo petrol",
        power: "95 hp",
        consumption: "5.2 L/100 km",
        bootSize: "351 L",
        length: "4,074 mm",
        topSpeed: "187 km/h",
        acceleration: "10.8s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["TGD short stays", "Solo travellers", "Capital weekends"],
      suitability: "Two travellers with carry-on bags, an easy collect at Podgorica Airport and a no-drama run through the capital's wide boulevards.",
      regional: "Slips into the kerbside bays on Njegoševa and Bokeška without anxiety, takes the Bar–Podgorica motorway at steady 120, and handles the 25 km down to Virpazar on Skadar Lake as a single easy half-hour.",
    },
    {
      id: 2,
      slug: "renault-clio",
      typeGroup: "economy",
      name: "Renault Clio",
      category: "Economy",
      tagline: "The default TGD pickup, cheap to fuel, comfortable on the Sozina motorway",
      lede: "The most-rented hatch at Podgorica Airport. Five doors, 391-litre boot, happy on the coast-bound motorway.",
      price: 28,
      image: "/img/fleet/renault-clio.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Bluetooth Audio","USB Charging","Central Locking","Touchscreen Display"],
      details: {
        engine: "1.0 TCe 3-cyl turbo petrol",
        power: "100 hp",
        consumption: "5.3 L/100 km",
        bootSize: "391 L",
        length: "4,050 mm",
        topSpeed: "188 km/h",
        acceleration: "11.8s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: true,
      bestFor: ["TGD arrivals", "Skadar Lake day-trippers","Short coastal hops"],
      suitability: "Two travellers flying into Podgorica who want a car that handles the Sozina tunnel run to Budva in the morning and Ostrog in the afternoon.",
      regional: "Comfortable on the E80 out through Podgorica's flat grid, eats the Sozina toll motorway south to Bar at 110 km/h, and parks on the Blok 5 side streets without scraping. The standard-issue inland Montenegrin rental.",
    },
    {
      id: 3,
      slug: "peugeot-308",
      typeGroup: "midsize",
      name: "Peugeot 308",
      category: "Mid-Size",
      tagline: "Diesel auto for the capital-to-mountains loops, Ostrog, Durmitor, Biogradska",
      lede: "Quiet BlueHDi diesel, 412-litre boot, 8-speed auto. The car you want for the new Smokovac motorway up to Kolašin.",
      price: 38,
      image: "/img/fleet/peugeot-308.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Automatic Transmission", "Adaptive Cruise", "Dual-Zone Climate", "Large Boot"],
      details: {
        engine: "1.5 BlueHDi 4-cyl diesel",
        power: "130 hp",
        consumption: "4.4 L/100 km",
        bootSize: "412 L (1,309 L seats folded)",
        length: "4,367 mm",
        topSpeed: "206 km/h",
        acceleration: "10.1s (0–100 km/h)",
        driveType: "Front-wheel drive, 8-spd auto",
      },
      popular: false,
      bestFor: ["Families of four", "Capital-to-Durmitor drivers", "Cross-border trips"],
      suitability: "Four adults with hold luggage, or a family working the full Podgorica–Kolašin–Žabljak loop. Diesel plus auto is the combination for long canyon days.",
      regional: "Settles at 1,800 rpm on the new Smokovac–Mateševo motorway section to Kolašin, hauls hiking gear through the Tara canyon approach, and returns an honest 5.0 L/100 km on the mixed inland and coastal miles.",
    },
    {
      id: 4,
      slug: "renault-megane",
      typeGroup: "midsize",
      name: "Renault Megane",
      category: "Mid-Size",
      tagline: "Biggest-boot hatch for Podgorica families heading north or to Bar",
      lede: "434-litre boot, soft long-distance damping, still-common on TGD fleets, the value distance-eater.",
      price: 36,
      image: "/img/fleet/renault-megane.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Large Boot","Bluetooth Audio","Cruise Control","Parking Sensors"],
      details: {
        engine: "1.5 Blue dCi 4-cyl diesel",
        power: "115 hp",
        consumption: "4.3 L/100 km",
        bootSize: "434 L",
        length: "4,360 mm",
        topSpeed: "195 km/h",
        acceleration: "11.1s (0–100 km/h)",
        driveType: "Front-wheel drive, 6-spd manual",
      },
      popular: false,
      bestFor: ["Four-up Podgorica families","TGD airport transfers","Long inland tours"],
      suitability: "A family of four with full-size cases that the Clio can't swallow. Older-generation cabin, but the boot genuinely earns its keep on the 2.5-hour push to Žabljak.",
      regional: "The 434-litre boot takes a pushchair, beach kit for Ulcinj and a cool-bag from Plantaže cellars in one load. Manual diesel is thrifty on the flat Podgorica–Bar run via Sozina, comfortable at 120 in top gear.",
    },
    {
      id: 5,
      slug: "kia-stonic",
      typeGroup: "suv",
      name: "Kia Stonic",
      category: "Compact Crossover",
      tagline: "Raised ride for the Podgorica back roads, Ostrog, Rijeka Crnojevića, Kosovo border",
      lede: "352-litre boot, higher ride than a hatch, small 1.0-litre turbo petrol, the budget crossover for inland detours.",
      price: 40,
      image: "/img/fleet/kia-stonic.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Raised Ride Height","Apple CarPlay","Reversing Camera","Lane Keep Assist"],
      details: {
        engine: "1.0 T-GDi 3-cyl turbo petrol",
        power: "100 hp",
        consumption: "5.5 L/100 km",
        bootSize: "352 L (1,155 L seats folded)",
        length: "4,140 mm",
        topSpeed: "183 km/h",
        acceleration: "10.7s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Ostrog pilgrims","Skadar Lake wine road","Kosovo-via-Rožaje drivers"],
      suitability: "Renters who want a higher driving position and a little more ground clearance for the M9 climb to Ostrog or the Rožaje road to Kosovo, without paying full SUV money.",
      regional: "The extra ride height takes the edge off the broken M9 stretches up to Ostrog, clears the rough unpaved spurs around Rijeka Crnojevića on the Skadar wine trail, and carries a couple's weekend gear to Kolašin without rattling. Front-wheel drive only, chains in winter above 1,000 m.",
    },
    {
      id: 6,
      slug: "vw-golf",
      typeGroup: "midsize",
      name: "VW Golf",
      category: "Mid-Size",
      tagline: "DSG diesel benchmark, the Podgorica all-rounder that does every itinerary",
      lede: "Polo's agility, 308's distance refinement, the default sensible pick for mixed capital, coast and mountain miles.",
      price: 42,
      image: "/img/fleet/vw-golf.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["DSG Automatic", "Adaptive Cruise", "Digital Cockpit", "Apple CarPlay"],
      details: {
        engine: "2.0 L TDI diesel (Mk8)",
        power: "150 hp",
        consumption: "4.3 L/100 km",
        bootSize: "381 L (1,237 L seats folded)",
        length: "4,287 mm",
        topSpeed: "223 km/h",
        acceleration: "8.4s (0–100 km/h)",
        driveType: "Front-wheel drive, 7-spd DSG auto",
      },
      popular: false,
      bestFor: ["Couples doing full MNE loops", "Mixed capital + coast itineraries", "Fast airport transfers"],
      suitability: "Couples or small families who want a car equally at home on Podgorica boulevards, the Sozina motorway and the Morača canyon climb, without committing to a bigger mid-size.",
      regional: "Cruises the Bar–Podgorica motorway at an effortless 120 km/h in DSG seventh, handles the Platije gorge climb to Kolašin without the driver reading for gears, and returns real 5.0 L/100 km on the mixed run to Ulcinj and back.",
    },
    {
      id: 7,
      slug: "toyota-yaris",
      typeGroup: "economy",
      name: "Toyota Yaris",
      category: "Economy",
      tagline: "Cheapest to fuel in the fleet, hybrid drivetrain for Podgorica's stop-start heat",
      lede: "3.8 L/100 km in real use. Silent electric crawl through the capital's 40°C summer traffic, no battery anxiety.",
      price: 34,
      image: "/img/fleet/toyota-yaris.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Hybrid",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Hybrid Drivetrain","Reversing Camera","Apple CarPlay","Adaptive Cruise"],
      details: {
        engine: "1.5 VVT-i Hybrid petrol–electric",
        power: "116 hp combined",
        consumption: "3.8 L/100 km",
        bootSize: "286 L",
        length: "3,940 mm",
        topSpeed: "175 km/h",
        acceleration: "9.7s (0–100 km/h)",
        driveType: "Front-wheel drive (e-CVT)",
      },
      popular: true,
      bestFor: ["Fuel-conscious capital renters","City-focused stays","Summer heat drivers"],
      suitability: "Travellers who want the strongest-possible AC in a Podgorica July, electric-mode silence in grid-lock traffic, and the fuel bill of half a Megane.",
      regional: "Crawls the Moskovska rush-hour queue on electric alone, glides the flat Sozina motorway down to Bar without touching the fuel needle, and the electric-powered AC stays arctic-cold even when the city cracks 40°C. Avoid for Žabljak weekends, the battery drains on the long climb.",
    },
  ],

  features: [
    { icon: "map-pin", title: "Airport Pickup", description: "Keys in hand within 10 minutes of landing at TGD. The mountains are waiting." },
    { icon: "shield-check", title: "Full Insurance", description: "Full coverage with zero excess option, built for mountain switchbacks, canyon roads, and everything in between." },
    { icon: "clock", title: "24/7 Support", description: "Snowed in above \u017dabljak? We've seen it before. Call any time." },
    { icon: "ban", title: "No Hidden Fees", description: "Winter extras like snow chains are priced upfront, never added at the counter. What you see is what you pay." },
    { icon: "refresh-cw", title: "Free Cancellation", description: "Ryanair rescheduled? Mountain pass closed by snow? Cancel up to 24 hours before for a full refund." },
    { icon: "globe", title: "Cross-Border", description: "Serbia (Prijepolje, 2 hrs), Albania (Shkodra, 1.5 hrs), Kosovo (Pe\u0107, 3 hrs), Green Card included, just tell us at booking." },
  ],

  testimonials: [
    { name: "Erik & Marte Solberg", location: "Oslo, Norway", text: "We flew into TGD specifically to hike Durmitor and walk the rim of Tara Canyon. The 4x4 was ready in minutes and handled the mountain roads to \u017dabljak without a single complaint. Booking was simple and the price was better than anything we found back home.", rating: 5, avatar: "/img/avatar-1.webp" },
    { name: "Lukas Berger", location: "Vienna, Austria", text: "Solo road trip from Podgorica Airport up through Mora\u010Da Canyon to Ostrog Monastery, one of the most dramatic drives I've ever done. The car was immaculate and picking it up at TGD took less than 10 minutes. I'll use this service every time I fly Wizz Air into Montenegro.", rating: 5, avatar: "/img/avatar-2.webp" },
    { name: "Beatriz & Joana", location: "Lisbon, Portugal", text: "We booked a beach trip but ended up spending two days exploring Lake Skadar wine villages and somehow found ourselves on a mountain road above Cetinje at sunset. Best accidental detour ever. The car made it all possible and the booking was completely stress-free.", rating: 5, avatar: "/img/avatar-3.webp" },
  ],

  faq: [
    { q: "What documents do I need?", a: "A valid driving licence showing Latin-script details, your passport, and a physical credit card issued in the main driver's name. If your licence was issued outside the EU, an International Driving Permit is strongly recommended alongside your national licence. Photocopies and digital licences stored on a phone are not accepted at pickup." },
    { q: "Can I drive to Serbia or Albania?", a: "Yes \u2014 cross-border travel is permitted to Serbia, Albania, Kosovo, Bosnia, and Croatia. The main border crossings near Podgorica are Dra\u010Denovac for Serbia and Hani i Hotit for Albania. Let us know at booking so we can prepare the Green Card and any additional paperwork in advance." },
    { q: "Is there a minimum age?", a: "The minimum rental age is 21, with at least 2 years of driving experience. Drivers aged 21\u201324 pay a young driver supplement; the exact rate depends on the vehicle category and is shown clearly during the search before you confirm anything." },
    { q: "What's included in the price?", a: "All vehicles include third-party liability insurance, and most include CDW (Collision Damage Waiver) in the base rate. VAT, the mandatory equipment kit (first aid, warning triangle, reflective vest), and a clearly stated fuel policy are all included. Mileage terms vary by vehicle and are shown before booking. Zero-excess upgrades are available as an add-on." },
    { q: "How does pickup work at TGD?", a: "Podgorica Airport (TGD) is a compact single-terminal building \u2014 arrivals are straightforward. Our agent meets you in the arrivals hall holding a board with your name. The car is parked just outside the terminal. From wheels-down to driving away typically takes under 10 minutes." },
    { q: "Can I drop off at a different location?", a: "Yes \u2014 one-way rentals are available across 28 destinations in Montenegro. Choose your preferred pickup and dropoff points during booking. One-way fees, where they apply, are shown transparently before you confirm." },
    { q: "What is the cancellation policy?", a: "Standard vehicles: free cancellation up to 7 days before pickup. Luxury cars and convertibles: free cancellation up to 30 days before. A 6% payment processing fee applies to all cancellations regardless of timing. If a mountain pass closure or severe weather forces a change of plans, contact us \u2014 we'll do what we can." },
    { q: "Is a deposit required?", a: "Deposit requirements at TGD vary between zero and \u20AC300 depending on the vehicle tier. The deposit must be blocked on a physical credit card (not debit or prepaid) in the main driver's name at the time of pickup, and is fully released once the car is returned undamaged. The exact amount for your chosen vehicle is shown in the booking summary." },
    { q: "What happens if I exceed the mileage limit?", a: "Vehicles with a kilometre cap charge a per-km rate for any distance above the agreed limit. The rate is listed in the vehicle terms before you book. If you're planning long mountain drives \u2014 Durmitor, Tara Canyon, the Albanian border \u2014 check the mileage terms carefully or look for an unlimited-mileage option." },
    { q: "Do I need snow chains for mountain roads?", a: "From November to March, snow chains or winter tyres are legally required on mountain roads above 1,000 m in Montenegro. This includes the road to \u017dabljak and Durmitor National Park. If you're heading into the mountains in winter, let us know at booking and we'll equip the car accordingly. Also note: Nik\u0161i\u0107 is the last reliable fuel stop before Durmitor \u2014 fill up there." },
    { q: "How much do I pay upfront?", a: "A deposit of 15\u201320% of the total rental cost is charged at booking to secure your reservation. The remaining balance is settled directly with the rental agent at TGD pickup. No surprise charges at the counter \u2014 the split is shown clearly before you confirm." },
    { q: "Can I rent without a credit card?", a: "A small number of vehicles in our fleet are available to renters without a credit card \u2014 these are clearly marked in the search results. For most vehicles, however, a physical credit card in the driver's name is required for the security deposit at pickup." },
  ],

  locations: [
    { name: "Podgorica Airport", tag: "Most Popular" },
    { name: "City Centre", tag: "" },
    { name: "Millennium Bridge Area", tag: "" },
  ],

  destinations: [
    {
      name: "Podgorica Airport",
      slug: "podgorica-airport",
      tag: "Most Popular",
      desc: "Our main hub. We meet you at arrivals.",
      image: "/img/podgorica-airport.webp",
    },
    {
      name: "Lake Skadar",
      slug: "lake-skadar",
      tag: "30 Minutes",
      desc: "The Balkans' largest lake and a national park.",
      image: "/img/lake-skadar.webp",
    },
    {
      name: "Cetinje",
      slug: "cetinje",
      tag: "35 Minutes",
      desc: "Montenegro's old royal capital in the mountains.",
      image: "/img/cetinje-town.webp",
    },
    {
      name: "Budva",
      slug: "budva",
      tag: "1 Hour",
      desc: "Riviera beaches and the old town walls.",
      image: "/img/budva-coast.webp",
    },
    {
      name: "Kotor",
      slug: "kotor",
      tag: "1.5 Hours",
      desc: "UNESCO walled city on the Bay of Kotor.",
      image: "/img/kotor-bay.webp",
    },
    {
      name: "Durmitor",
      slug: "durmitor",
      tag: "2.5 Hours",
      desc: "UNESCO national park, mountains, lakes, and canyons.",
      image: "/img/durmitor-mountains.webp",
    },
    {
      name: "Ostrog Monastery",
      slug: "ostrog-monastery",
      tag: "45 Minutes",
      desc: "Cliff-carved monastery, Montenegro's most visited pilgrimage site.",
      image: "/img/ostrog-monastery.webp",
    },
    {
      name: "Niksic",
      slug: "niksic",
      tag: "1 Hour",
      desc: "Montenegro's second city, gateway to the north.",
      image: "/img/niksic-town.webp",
    },
  ],
};

export default siteConfig;
